### PR TITLE
Extendible Address Encoding support

### PR DESCRIPTION
**Pull request by pelle**
WIP don't merge yet

- [x] uses eae (extendible address encoding) for addresses instead of hex
- [x] uses correct json-rpc endpoint and registry based on network in encoding
- [x] main
- [x] ropsten
- [ ] kovan
- [ ] infuranet
- [x] better tests
- [x] update README
- [x] support legacy addresses on old registry on ropsten

### CODE REVIEW

**Comment by zachferland** [comment]
Does get now only consume eae encoded addresses? Given that I will still be dealing with default addresses everywhere else I assume I now need always encode them with the network I know I am on? if this it the case how do I know how to encode issuer and subject addresses? Should there also be an encode function made available? Do we plan to encode addresses higher up in one of the other libs?

**Comment by pelle** [comment]
@zachferland https://github.com/uport-project/eae/pull/2/files encodes it. I'm going to add support for old legacy addresses as well later today. I was just thinking about it, it makes life easier.

**Comment by zachferland** [comment]
@pelle alright cool didn't see that, and yeah I think that makes a lot of sense. At least in our libs do we want to encode addresses anywhere?

**Comment by zachferland** [comment]
Do we imagine that this library will primarily be used in our own libs and not independently? if so this looks good. If not, I was originally thinking you could call the new registry, not just the old registry with addresses not encoded with the network. I would also want to be able to specify the network and not be given a default set of networks which could be called (the optional network arg joins the sets)

**Comment by pelle** [comment]
It's mostly in our libraries. We should do this as a major release. If you need to support the old registry on a different network (probably very few people need this) they can continue to use the older versions.

I would like to remove this old registry support from the code in a couple of months time.

**Comment by zachferland** [comment]
@pelle 👍 yeah sounds good, if ever used more independently i think we want itto accept normal addresses (for the new registry), unless everyone's encodes addresses like this :) and I would not want it to fetch and return a profile from 1 of x networks. Yeah this should be a major release an I can update uport-connect

**Pull request merged**
